version: '3.7'

services:
  postgres:
    image: postgres:14.1
    ports:
      - '8090:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: artikool
      POSTGRES_PASSWORD: "l91gP_ezYjrakBbXvCy_UmxrpyMCMJUu"
    volumes:
      - artikool_data:/var/lib/postgresql/data
  redis:
    image: redis:6.2.6
    ports:
      - '8091:6379'
    command: redis-server --requirepass "qdWTxj7NLnzBMpHDkls8NOthdA7qw51t"
    environment:
      - REDIS_REPLICATION_MODE=master
volumes:
  artikool_data:
